services:
  postgres:
    image: postgres:15
    container_name: shopnow_postgres
    restart: always
    environment:
      POSTGRES_USER: shopnow
      POSTGRES_PASSWORD: shopnowpassword
      POSTGRES_DB: shopnow_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ../db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql

volumes:
  postgres_data: